from utils.transit_logic import transit_logic
from simulation.program_2 import *

if __name__ == "__main__":
    # from simulation.program_1 import *
    # transit_logic(
    #     USE_OF_THE_BLASTING_ROOM = USE_OF_THE_BLASTING_ROOM,
    #     NUMBER_OF_METRO_DROP_OFF = NUMBER_OF_METRO_DROP_OFF,
    #     APPROACH_QUEUE = APPROACH_QUEUE,
    #     NUMBER_OF_INCOMING_VEHICLES_PER_DAY = NUMBER_OF_INCOMING_VEHICLES_PER_DAY,
    #     NUMBER_OF_TRANS_SHIPMENT_VEHICLES = NUMBER_OF_TRANS_SHIPMENT_VEHICLES, 
    #     ENABLING_SEPARATION_OF_TRANSFER_VEHICLES = ENABLING_SEPARATION_OF_TRANSFER_VEHICLES,
    #     STATIONS_SERVICED_BY_TRANSFER_VANS = STATIONS_SERVICED_BY_TRANSFER_VANS,
    #     ALL_STAGE_CONFIG = ALL_STAGE_CONFIG
    # )

    transit_logic(
        USE_OF_THE_BLASTING_ROOM = USE_OF_THE_BLASTING_ROOM,
        NUMBER_OF_METRO_DROP_OFF = NUMBER_OF_METRO_DROP_OFF,
        APPROACH_QUEUE = APPROACH_QUEUE,
        NUMBER_OF_INCOMING_VEHICLES_PER_DAY = NUMBER_OF_INCOMING_VEHICLES_PER_DAY,
        NUMBER_OF_TRANS_SHIPMENT_VEHICLES = NUMBER_OF_TRANS_SHIPMENT_VEHICLES, 
        ENABLING_SEPARATION_OF_TRANSFER_VEHICLES = ENABLING_SEPARATION_OF_TRANSFER_VEHICLES,
        STATIONS_SERVICED_BY_TRANSFER_VANS = STATIONS_SERVICED_BY_TRANSFER_VANS,
        ALL_STAGE_CONFIG = ALL_STAGE_CONFIG
    )